**PyTorch Basics: Tensor & Gradients**

**Torch:**
- A tensor is a number, vector, matrix or any n-dimensional array.

In [1]:
#@ Loading the library
import torch
import numpy as np

In [2]:
#@ Creating a tensor with a single number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
#@ Checking the data type
t1.dtype

torch.float32

In [4]:
#@ Creating more complex tensors: Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
#@ Creating matrix
t3 = torch.tensor([[5., 6],
                  [7, 8],
                  [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
#@ Creating 3 - Dimensional Array
t4 = torch.tensor([
    [[1, 2, 3],
    [4, 5, 6]],
    [[10, 11, 12],
    [13, 14, 15]]
])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 11, 12],
         [13, 14, 15]]])

Tensor can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor

In [7]:
#@ Checking the shape of all tensors
print('The shape of t1 is:', t1.shape)
print('The shape of t2 is:', t2.shape)
print('The shape of t3 is:', t3.shape)
print('The shape of t4 is:', t4.shape)

The shape of t1 is: torch.Size([])
The shape of t2 is: torch.Size([4])
The shape of t3 is: torch.Size([3, 2])
The shape of t4 is: torch.Size([2, 2, 3])


**Tensor Operations and Gradients**

In [8]:
#@ Creating tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [9]:
#@ Applying arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [10]:
#@ Computing derivatives
y.backward()

In [11]:
#@ Displaying the gradients
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/dw', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/dw tensor(1.)


- As expected, dy/dw has the same value as x i.e. 3, and dy/db has the value 1. Note that x.grad is None, because x doesn't have requires_grad set to True.

- The "grad" in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

In [12]:
x = np.array([[1, 2], [3, 4.]])

In [13]:
#@ Conveting numpy array into torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [14]:
#@ Checking numpy array and torch tensor data types
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [15]:
#@ Converting torch tensor to numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is really important because most datasets we will work with is likely to be read and preprocessed as Numpy arrays